workspace:
  root: ./
create:
  template: template_model
  data:
    db: jet
    run_in_start_at: 7000
    run_out_start_at: 8000
  sampler:
    method: latin-hypercube
    n_samples: 3
  matrix:
    - ids: profiles_1d/0/zeff
      operator: add
      values: [1, 2, 3]
    - ids: profiles_1d/0/t_i_average
      operator: multiply
      values: [1.1, 1.2, 1.3]
status:
  msg_completed: 'Status : Completed successfully'
  msg_failed: 'Status : Failed'
  msg_running: 'Status : Running'
submit:
  status_file: jetto.status
  submit_script_name: .llcmd
plot:
  plots:
  - add_time_slider: false
    x: null
    xlabel: null
    y: profiles_1d/0/electrons/density_thermal
    ylabel: null
