plot:  # Configuration for the plotting subcommand
  plots:
  - x:  # data on x-axis, default is rho-thoroidal
    y: profiles_1d/0/electrons/density_thermal # data on y-axis
    xlabel: # custom label for x-axis
    ylabel: # custom label for y-axis
create: # Configuration for the create subcommand
  matrix:  # Defines the space to sample
  - ids: profiles_1d/0/t_i_average  # field within ids described in template dir from which to sample
    operator: multiply # Operation used for sampling
    values: # values to use with operator on field to create sampling space
    - 1.1
    - 1.2
    - 1.3
  sampler:
    method: latin-hypercube  # Method to select samples, default: latin-hypercube, also supports: latin-hypercube, halton, sobol, cartesian-product
    n_samples: 1 # Number of samples to take
  template: /pfs/work/g2ssmee/jetto/runs/duqtools_template # jetto run-case to use as template for all the other runs
workspace:
  root: ./  # The folder from which experiments have to be run, rjettov runs relative to this folder
