create:
  matrix:
  - ids: profiles_1d/0/t_i_average
    operator: multiply
    values:
    - 1.1
    - 1.2
    - 1.3
  sampler:
    method: cartesian-product
  template: /pfs/work/g2ssmee/jetto/runs/duqtools_template
plot:
  plots:
  - add_time_slider: false
    x: null
    xlabel: null
    y: profiles_1d/0/electrons/density_thermal
    ylabel: null
workspace:
  root: /pfs/work/g2vazizi/jetto/runs/
