workspace: ./workspace
create:
  template:
    db: jet
    run: 1
    shot: 92432
    user: g2aho
  data:
    db: uq_run
    run_in_start_at: 7000
    run_out_start_at: 8000
  matrix:
    - ids: zeff
      operator: add
      values: [1, 2, 3]
    - ids: t_i_average
      operator: multiply
      values: [1.1, 1.2, 1.3]
